### PR TITLE
Fixed typos and some grammatical flaws ...

### PR DESCRIPTION
**Pull request by mwittig**
* Fixed typos and some grammatical flaws
* Changed Formatting is a few places, in the "example" document in particular
* Added space after ### and ## markers to provide for correct transformation to HTML headings

I have hust picked some of the low hanging fruits here. So far, I have not added anything new to the documentation.

### CODE REVIEW

**Comment by mwittig** [comment]
Just wondering: The API guide is very short and appears to be missing parts. For example, via google I can find http://pimatic.org/api/actions/ which does not appear to be part of the guide. Did I miss something?

**Comment by sweetpi** [comment]
Thank you very much for the corrections. It looks much much better now :)

> Just wondering: The API guide is very short and appears to be missing parts. For example, via google I can find http://pimatic.org/api/actions/ which does not appear to be part of the guide. Did I miss something?

The api reference gets generated from the api.coffee file and is therefore not part of the guide. But there should be an link in the api guide.

**Comment by sweetpi** [comment]
I've updated the webpage with your changes (may need an explicit reload to be displayed).

**Comment by mwittig** [comment]
Great, thanks!

**Comment by mwittig** [comment]
@sweetpi One more thing I haven't covered yet. In several places wordings like "pimatics development guide" or "in pimatics output" are used. However, this is not correct as the possesive form must be used, i.e. "pimatic's" or the wording must be changed to avoid the possessive form, e.g. "the pimatic development guide" or "the developement guide of pimatic". What do you prefer? Personally, I think possesive form is ok in the common case. I am happy to do the necessary changes.

**Comment by sweetpi** [comment]
Thank you pointing this out. I'm happy with both. I think we should choose the form situation dependent. 

 * "in pimatic's output", because the output is of pimatic
 *  "the developement guide *for* pimatic", because the guide is more for pimatic, than pimatic's guide.

**Pull request merged**
